//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THFinance
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public string EMP_NAME { get; set; }
        public int EMP_ORGID { get; set; }
        public int EMP_DEPTID { get; set; }
        public int EMP_TECHID { get; set; }
        public string EMP_SALRY { get; set; }
        public string EMP_EMAIL { get; set; }
        public System.DateTime EMP_JOINDATE { get; set; }
        public int ID { get; set; }
    }
}
