//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THFinance
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_payment
    {
        public int payId { get; set; }
        public int branchId { get; set; }
        public int managerId { get; set; }
        public int totalPayment { get; set; }
        public System.DateTime prepayDate { get; set; }
        public System.DateTime presentDate { get; set; }
        public int paidAmount { get; set; }
        public int name { get; set; }
        public int remainingAmount { get; set; }
        public Nullable<int> paymentmethod { get; set; }
        public string remainingdays { get; set; }
    }
}
