//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THFinance
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_LoanType
    {
        public int LoanId { get; set; }
        public int LoanBorrowerId { get; set; }
        public Nullable<System.DateTime> dateofLoan { get; set; }
        public Nullable<System.DateTime> LoanendDate { get; set; }
        public string TypeOfVehicle { get; set; }
        public Nullable<int> AmountOfLoan { get; set; }
        public Nullable<int> Periods { get; set; }
        public Nullable<int> RateofInterest { get; set; }
        public Nullable<int> monthlyInstalllment { get; set; }
    }
}
