//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THFinance
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PaymentType
    {
        public int paymentId { get; set; }
        public int paymentBorrowerId { get; set; }
        public string PaymentType { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public int PaymentAmount { get; set; }
        public string givenamount { get; set; }
        public Nullable<int> paymentmethod { get; set; }
        public string monthlyInterest { get; set; }
    }
}
