//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THFinance
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_managers
    {
        public int manage_id { get; set; }
        public string manager_name { get; set; }
        public int mgbrnch_id { get; set; }
    
        public virtual tbl_branches tbl_branches { get; set; }
    }
}
