//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THFinance
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_payee
    {
        public string name { get; set; }
        public int branchId { get; set; }
        public int managerId { get; set; }
        public string payeeProof { get; set; }
        public string NomineeName { get; set; }
        public string NomineeProof { get; set; }
        public int amount { get; set; }
        public System.DateTime startdate { get; set; }
        public System.DateTime enddate { get; set; }
        public int paymentmethod { get; set; }
        public int ID { get; set; }
        public Nullable<int> givenamount { get; set; }
    }
}
