//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THFinance
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_borrower
    {
        public int borrowerId { get; set; }
        public string borrowerName { get; set; }
        public string borrowerFatherName { get; set; }
        public string BorrowerDesignation { get; set; }
        public string borrowerPhone { get; set; }
        public string borrowerAddress { get; set; }
        public int modifiedyby { get; set; }
        public int createdby { get; set; }
        public System.DateTime createdDate { get; set; }
        public System.DateTime modifiedDate { get; set; }
        public string borrowerproofType { get; set; }
        public byte[] borrowerPhoto { get; set; }
        public byte[] borrowerproof { get; set; }
    }
}
