//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THFinance
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_borrowerPaymentmethod
    {
        public int borrowerPayid { get; set; }
        public int borrowerBranchid { get; set; }
        public int borrowerLoanid { get; set; }
        public System.DateTime borrowerPaymentdate { get; set; }
        public string borrowerPayamount { get; set; }
        public string borrowerReaminingamount { get; set; }
        public int borrowerPenalitydays { get; set; }
        public System.DateTime borrowerStartdate { get; set; }
        public int borrowerName { get; set; }
        public Nullable<int> borrowermanager { get; set; }
        public Nullable<int> createdby { get; set; }
        public Nullable<int> modified { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public Nullable<System.DateTime> modifieddate { get; set; }
        public string totalpayment { get; set; }
        public Nullable<int> status { get; set; }
    }
}
