//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THFinance
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Guarantor
    {
        public int GuarantorId { get; set; }
        public int GuarantorborrowerId { get; set; }
        public string GuarantorName { get; set; }
        public string GuarantorFatherName { get; set; }
        public string GuarantorPhone { get; set; }
        public string GuarantorAddress { get; set; }
        public Nullable<System.DateTime> G_createdDate { get; set; }
        public Nullable<System.DateTime> G_modifiedDate { get; set; }
        public Nullable<int> G_createdBy { get; set; }
        public Nullable<int> G_modifiedBy { get; set; }
        public string GuarantorProoftype { get; set; }
        public byte[] GuarantorProof { get; set; }
        public byte[] Guarantorphoto { get; set; }
        public string GuarantorDesignation { get; set; }
    }
}
