//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THFinance
{
    using System;
    using System.Collections.Generic;
    
    public partial class tble_Vehicle
    {
        public int VehicleId { get; set; }
        public string VehicleType { get; set; }
        public string Vehiclemodel { get; set; }
        public string VehicleChasisNo { get; set; }
        public string VehicleEngineNo { get; set; }
        public string VehicleBHP { get; set; }
        public string VehicleColor { get; set; }
        public string VehicleKeyNo { get; set; }
        public string VehicleInsurance { get; set; }
        public int VehicleBorroerId { get; set; }
    }
}
