//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THFinance
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class THFinanceEntities : DbContext
    {
        public THFinanceEntities()
            : base("name=THFinanceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<tbl_branches> tbl_branches { get; set; }
        public virtual DbSet<tbl_chitti> tbl_chitti { get; set; }
        public virtual DbSet<tbl_managers> tbl_managers { get; set; }
        public virtual DbSet<tbl_payee> tbl_payee { get; set; }
        public virtual DbSet<tbl_payment> tbl_payment { get; set; }
        public virtual DbSet<tbl_Borrowerpayment> tbl_Borrowerpayment { get; set; }
        public virtual DbSet<tbl_LoanType> tbl_LoanType { get; set; }
        public virtual DbSet<tbl_borrowerPaymentmethod> tbl_borrowerPaymentmethod { get; set; }
        public virtual DbSet<tbl_PaymentType> tbl_PaymentType { get; set; }
        public virtual DbSet<tble_Vehicle> tble_Vehicle { get; set; }
        public virtual DbSet<THF_User> THF_User { get; set; }
        public virtual DbSet<tbl_borrower> tbl_borrower { get; set; }
        public virtual DbSet<tbl_Guarantor> tbl_Guarantor { get; set; }
    }
}
